<?php

/**
 * Date: 19/08/2015
 * Time: 13:36
 */

use \zframework\AssetsManager;
$assetsManager = new AssetsManager();
?>

<style rel="stylesheet">

    body {
        background-color: #FFF;
    }

    .error-container{
        border: 1px solid #DCDCDC;
        position : absolute;
        border-radius: 5px;
        width: 620px;
        height: 300px;
        left: 50%;
        top: 50%;
        margin-left : -310px; /* half of the width  */
        margin-top  : -150px; /* half of the height */
        background-color: #F8F8FF;
        box-shadow: 5px 5px 5px #888888;
        z-index: 1;
    }

    .img_404 {
        position : absolute;
        left: 50%;
        top: 50%;
        margin-left : -50px; /* half of the width  */
        margin-top  : -255px; /* half of the height */
        z-index: 2;
    }

</style>

<div class="img_404">
    <?php
    $arrOptions = array(
        "id"=>"robot",
        "width"=>100,
        "height"=>120,
        "alt"=>"robot"
    );
    echo $assetsManager->loadImage("img/coruja.png", $arrOptions);
    ?>
</div>

<div class="error-container">

    <br/><br/><br/>

    <div class="row">

        <div class="col-md-4" style="text-align: center; border-right: 5px solid #EEEEEE;">
            <h1 style="color: #668CB3">404</h1>
            <h2><small>Página não encontrada!</small></h2>
        </div>

        <div class="col-md-7" style="text-align: justify">
            <h3>Desculpe!</h3>
            <h5>A página que você procura não existe em nosso servidor.</h5>
                <p>Clique <a href="#">aqui</a> para ir à página inicial.</p>
        </div>



    </div>

</div>